///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssignmentModel {
/*
{
  "subject": "english",
  "class": "8-A",
  "title": "Essay on Global Warming",
  "desc": "Write an essay discussing the impact of global warming on the environment.",
  "totalMarks": "50",
  "dueDate": "2023-12-01",
  "uploadFile": "https://example.com/global-warming-essay.pdf",
  "isAssign": true,
  "isSubmit": false
} 
*/

  String? subject;
  String? theClass;
  String? title;
  String? desc;
  String? totalMarks;
  String? dueDate;
  String? uploadFile;
  bool? isAssign;
  bool? isSubmit;

  AssignmentModel({
    this.subject,
    this.theClass,
    this.title,
    this.desc,
    this.totalMarks,
    this.dueDate,
    this.uploadFile,
    this.isAssign,
    this.isSubmit,
  });
  AssignmentModel.fromJson(Map<String, dynamic> json) {
    subject = json['subject']?.toString();
    theClass = json['class']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    totalMarks = json['totalMarks']?.toString();
    dueDate = json['dueDate']?.toString();
    uploadFile = json['uploadFile']?.toString();
    isAssign = json['isAssign'];
    isSubmit = json['isSubmit'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subject'] = subject;
    data['class'] = theClass;
    data['title'] = title;
    data['desc'] = desc;
    data['totalMarks'] = totalMarks;
    data['dueDate'] = dueDate;
    data['uploadFile'] = uploadFile;
    data['isAssign'] = isAssign;
    data['isSubmit'] = isSubmit;
    return data;
  }
}
