///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssignmentCompletionModelDataAllAssignmentsAssignmentId {
/*
{
  "_id": "65dec27aa78d5a563714e225",
  "subject": "6570261b8c2337e8d3e2e313",
  "class": "65d3019042db28a52371cb71",
  "title": "Essay on Global Warming",
  "desc": "Write an essay discussing the impact of global warming on the environment.",
  "totalMarks": "50",
  "dueDate": "2023-12-01T00:00:00.000Z",
  "uploadFile": "https://example.com/global-warming-essay.pdf",
  "isAssign": true,
  "isSubmit": false,
  "isDeleted": false,
  "createdAt": "2024-02-28T05:19:54.586Z",
  "updatedAt": "2024-02-28T05:19:54.586Z",
  "__v": 0
} 
*/

  String? Id;
  String? subject;
  String? theClass;
  String? title;
  String? desc;
  String? totalMarks;
  String? dueDate;
  String? uploadFile;
  bool? isAssign;
  bool? isSubmit;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  AssignmentCompletionModelDataAllAssignmentsAssignmentId({
    this.Id,
    this.subject,
    this.theClass,
    this.title,
    this.desc,
    this.totalMarks,
    this.dueDate,
    this.uploadFile,
    this.isAssign,
    this.isSubmit,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  AssignmentCompletionModelDataAllAssignmentsAssignmentId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    theClass = json['class']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    totalMarks = json['totalMarks']?.toString();
    dueDate = json['dueDate']?.toString();
    uploadFile = json['uploadFile']?.toString();
    isAssign = json['isAssign'];
    isSubmit = json['isSubmit'];
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class AssignmentCompletionModelDataAllAssignments {
/*
{
  "_id": "65dec790562ab2eb554b207e",
  "studentId": "65701e37b9cdbf994405ddae",
  "assignmentId": {
    "_id": "65dec27aa78d5a563714e225",
    "subject": "6570261b8c2337e8d3e2e313",
    "class": "65d3019042db28a52371cb71",
    "title": "Essay on Global Warming",
    "desc": "Write an essay discussing the impact of global warming on the environment.",
    "totalMarks": "50",
    "dueDate": "2023-12-01T00:00:00.000Z",
    "uploadFile": "https://example.com/global-warming-essay.pdf",
    "isAssign": true,
    "isSubmit": false,
    "isDeleted": false,
    "createdAt": "2024-02-28T05:19:54.586Z",
    "updatedAt": "2024-02-28T05:19:54.586Z",
    "__v": 0
  },
  "answers": "this is the answer of assigment",
  "uploadPdf": "",
  "submissionDate": "2024-02-28T05:41:36.868Z",
  "isSubmitted": true,
  "createdAt": "2024-02-28T05:41:36.875Z",
  "updatedAt": "2024-02-28T05:41:36.875Z",
  "__v": 0
} 
*/

  String? Id;
  String? studentId;
  AssignmentCompletionModelDataAllAssignmentsAssignmentId? assignmentId;
  String? answers;
  String? uploadPdf;
  String? submissionDate;
  bool? isSubmitted;
  String? createdAt;
  String? updatedAt;
  int? V;

  AssignmentCompletionModelDataAllAssignments({
    this.Id,
    this.studentId,
    this.assignmentId,
    this.answers,
    this.uploadPdf,
    this.submissionDate,
    this.isSubmitted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  AssignmentCompletionModelDataAllAssignments.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    studentId = json['studentId']?.toString();
    assignmentId = (json['assignmentId'] != null) ? AssignmentCompletionModelDataAllAssignmentsAssignmentId.fromJson(json['assignmentId']) : null;
    answers = json['answers']?.toString();
    uploadPdf = json['uploadPdf']?.toString();
    submissionDate = json['submissionDate']?.toString();
    isSubmitted = json['isSubmitted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class AssignmentCompletionModelDataImprovementsTeacherDetails {
/*
{
  "contactNumber": "9100000000",
  "role": "user",
  "_id": "657021118c2337e8d3e2e307",
  "joiningDate": "2023-12-06T07:20:35.124Z",
  "experience": "",
  "address": "",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "dob": "31",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Teachers",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2024-01-18T12:51:02.503Z",
  "__v": 0,
  "school": "65a52f67e6b1f330a3d7673d"
} 
*/

  String? contactNumber;
  String? role;
  String? Id;
  String? joiningDate;
  String? experience;
  String? address;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? school;

  AssignmentCompletionModelDataImprovementsTeacherDetails({
    this.contactNumber,
    this.role,
    this.Id,
    this.joiningDate,
    this.experience,
    this.address,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.school,
  });
  AssignmentCompletionModelDataImprovementsTeacherDetails.fromJson(Map<String, dynamic> json) {
    contactNumber = json['contactNumber']?.toString();
    role = json['role']?.toString();
    Id = json['_id']?.toString();
    joiningDate = json['joiningDate']?.toString();
    experience = json['experience']?.toString();
    address = json['address']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    school = json['school']?.toString();
  }
}

class AssignmentCompletionModelDataImprovements {
/*
{
  "improvement": "Work on time management",
  "teacherDetails": {
    "contactNumber": "9100000000",
    "role": "user",
    "_id": "657021118c2337e8d3e2e307",
    "joiningDate": "2023-12-06T07:20:35.124Z",
    "experience": "",
    "address": "",
    "name": "John Doe",
    "email": "teacher321@gmail.com",
    "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
    "gender": "Male",
    "dob": "31",
    "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
    "firebaseSignInProvider": "custom",
    "active": true,
    "isDeleted": false,
    "__t": "Teachers",
    "createdAt": "2023-12-06T07:21:53.404Z",
    "updatedAt": "2024-01-18T12:51:02.503Z",
    "__v": 0,
    "school": "65a52f67e6b1f330a3d7673d"
  }
} 
*/

  String? improvement;
  AssignmentCompletionModelDataImprovementsTeacherDetails? teacherDetails;

  AssignmentCompletionModelDataImprovements({
    this.improvement,
    this.teacherDetails,
  });
  AssignmentCompletionModelDataImprovements.fromJson(Map<String, dynamic> json) {
    improvement = json['improvement']?.toString();
    teacherDetails = (json['teacherDetails'] != null) ? AssignmentCompletionModelDataImprovementsTeacherDetails.fromJson(json['teacherDetails']) : null;
  }
}

class AssignmentCompletionModelData {
/*
{
  "studentId": "65701e37b9cdbf994405ddae",
  "submittedCount": 1,
  "totalAssignments": 1,
  "percentageSubmitted": "100.00%",
  "improvements": [
    {
      "improvement": "Work on time management",
      "teacherDetails": {
        "contactNumber": "9100000000",
        "role": "user",
        "_id": "657021118c2337e8d3e2e307",
        "joiningDate": "2023-12-06T07:20:35.124Z",
        "experience": "",
        "address": "",
        "name": "John Doe",
        "email": "teacher321@gmail.com",
        "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
        "gender": "Male",
        "dob": "31",
        "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
        "firebaseSignInProvider": "custom",
        "active": true,
        "isDeleted": false,
        "__t": "Teachers",
        "createdAt": "2023-12-06T07:21:53.404Z",
        "updatedAt": "2024-01-18T12:51:02.503Z",
        "__v": 0,
        "school": "65a52f67e6b1f330a3d7673d"
      }
    }
  ],
  "allAssignments": [
    {
      "_id": "65dec790562ab2eb554b207e",
      "studentId": "65701e37b9cdbf994405ddae",
      "assignmentId": {
        "_id": "65dec27aa78d5a563714e225",
        "subject": "6570261b8c2337e8d3e2e313",
        "class": "65d3019042db28a52371cb71",
        "title": "Essay on Global Warming",
        "desc": "Write an essay discussing the impact of global warming on the environment.",
        "totalMarks": "50",
        "dueDate": "2023-12-01T00:00:00.000Z",
        "uploadFile": "https://example.com/global-warming-essay.pdf",
        "isAssign": true,
        "isSubmit": false,
        "isDeleted": false,
        "createdAt": "2024-02-28T05:19:54.586Z",
        "updatedAt": "2024-02-28T05:19:54.586Z",
        "__v": 0
      },
      "answers": "this is the answer of assigment",
      "uploadPdf": "",
      "submissionDate": "2024-02-28T05:41:36.868Z",
      "isSubmitted": true,
      "createdAt": "2024-02-28T05:41:36.875Z",
      "updatedAt": "2024-02-28T05:41:36.875Z",
      "__v": 0
    }
  ]
} 
*/

  String? studentId;
  int? submittedCount;
  int? totalAssignments;
  String? percentageSubmitted;
  List<AssignmentCompletionModelDataImprovements?>? improvements;
  List<AssignmentCompletionModelDataAllAssignments?>? allAssignments;

  AssignmentCompletionModelData({
    this.studentId,
    this.submittedCount,
    this.totalAssignments,
    this.percentageSubmitted,
    this.improvements,
    this.allAssignments,
  });
  AssignmentCompletionModelData.fromJson(Map<String, dynamic> json) {
    studentId = json['studentId']?.toString();
    submittedCount = json['submittedCount']?.toInt();
    totalAssignments = json['totalAssignments']?.toInt();
    percentageSubmitted = json['percentageSubmitted']?.toString();
  if (json['improvements'] != null) {
  final v = json['improvements'];
  final arr0 = <AssignmentCompletionModelDataImprovements>[];
  v.forEach((v) {
  arr0.add(AssignmentCompletionModelDataImprovements.fromJson(v));
  });
    improvements = arr0;
    }
  if (json['allAssignments'] != null) {
  final v = json['allAssignments'];
  final arr0 = <AssignmentCompletionModelDataAllAssignments>[];
  v.forEach((v) {
  arr0.add(AssignmentCompletionModelDataAllAssignments.fromJson(v));
  });
    allAssignments = arr0;
    }
  }
}

class AssignmentCompletionModel {
/*
{
  "status": true,
  "data": {
    "studentId": "65701e37b9cdbf994405ddae",
    "submittedCount": 1,
    "totalAssignments": 1,
    "percentageSubmitted": "100.00%",
    "improvements": [
      {
        "improvement": "Work on time management",
        "teacherDetails": {
          "contactNumber": "9100000000",
          "role": "user",
          "_id": "657021118c2337e8d3e2e307",
          "joiningDate": "2023-12-06T07:20:35.124Z",
          "experience": "",
          "address": "",
          "name": "John Doe",
          "email": "teacher321@gmail.com",
          "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
          "gender": "Male",
          "dob": "31",
          "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
          "firebaseSignInProvider": "custom",
          "active": true,
          "isDeleted": false,
          "__t": "Teachers",
          "createdAt": "2023-12-06T07:21:53.404Z",
          "updatedAt": "2024-01-18T12:51:02.503Z",
          "__v": 0,
          "school": "65a52f67e6b1f330a3d7673d"
        }
      }
    ],
    "allAssignments": [
      {
        "_id": "65dec790562ab2eb554b207e",
        "studentId": "65701e37b9cdbf994405ddae",
        "assignmentId": {
          "_id": "65dec27aa78d5a563714e225",
          "subject": "6570261b8c2337e8d3e2e313",
          "class": "65d3019042db28a52371cb71",
          "title": "Essay on Global Warming",
          "desc": "Write an essay discussing the impact of global warming on the environment.",
          "totalMarks": "50",
          "dueDate": "2023-12-01T00:00:00.000Z",
          "uploadFile": "https://example.com/global-warming-essay.pdf",
          "isAssign": true,
          "isSubmit": false,
          "isDeleted": false,
          "createdAt": "2024-02-28T05:19:54.586Z",
          "updatedAt": "2024-02-28T05:19:54.586Z",
          "__v": 0
        },
        "answers": "this is the answer of assigment",
        "uploadPdf": "",
        "submissionDate": "2024-02-28T05:41:36.868Z",
        "isSubmitted": true,
        "createdAt": "2024-02-28T05:41:36.875Z",
        "updatedAt": "2024-02-28T05:41:36.875Z",
        "__v": 0
      }
    ]
  }
} 
*/

  bool? status;
  AssignmentCompletionModelData? data;

  AssignmentCompletionModel({
    this.status,
    this.data,
  });
  AssignmentCompletionModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? AssignmentCompletionModelData.fromJson(json['data']) : null;
  }
}