import 'package:teaching_with_purpose/app/data/models/assignment_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class AssignmentsListModel {
/*
{
  "status": true,
  "result": 13,
  "data": [
    {
      "_id": "65af75fce71353863248020a",
      "subject": "Chemistry",
      "class": "8-A",
      "title": "asFADFGsrhgrhgry",
      "desc": "etreetrfgzdg",
      "totalMarks": "AWTRewgfdg",
      "dueDate": "2024-01-23T00:00:00.000Z",
      "uploadFile": "https://angolazone.s3.ap-south-1.amazonaws.com/angolazone-english.pdf",
      "isAssign": true,
      "isSubmit": false,
      "isDeleted": false,
      "createdAt": "2024-01-23T08:17:00.300Z",
      "updatedAt": "2024-01-23T08:17:00.300Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<AssignmentModel?>? data;

  AssignmentsListModel({
    this.status,
    this.result,
    this.data,
  });
  AssignmentsListModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <AssignmentModel>[];
  v.forEach((v) {
  arr0.add(AssignmentModel.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
