///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class AssignmentModel {
/*
{
  "_id": "658e78ba5092cee4528feb57",
  "title": "Essay on Global Warming",
  "desc": "Write an essay discussing the impact of global warming on the environment.",
  "totalMarks": "50",
  "dueDate": "2023-12-01T00:00:00.000Z",
  "isAssign": true,
  "isSubmit": false,
  "isDeleted": false,
  "createdAt": "2023-12-29T07:43:54.786Z",
  "updatedAt": "2023-12-29T07:43:54.786Z",
  "__v": 0
} 
*/

  String? Id;
  String? title;
  String? desc;
  String? totalMarks;
  String? dueDate;
  bool? isAssign;
  bool? isSubmit;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  AssignmentModel({
    this.Id,
    this.title,
    this.desc,
    this.totalMarks,
    this.dueDate,
    this.isAssign,
    this.isSubmit,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  AssignmentModel.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    title = json['title']?.toString();
    desc = json['desc']?.toString();
    totalMarks = json['totalMarks']?.toString();
    dueDate = json['dueDate']?.toString();
    isAssign = json['isAssign'];
    isSubmit = json['isSubmit'];
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['title'] = title;
    data['desc'] = desc;
    data['totalMarks'] = totalMarks;
    data['dueDate'] = dueDate;
    data['isAssign'] = isAssign;
    data['isSubmit'] = isSubmit;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

