///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChapterModel {
/*
{
  "subjectId": "654c7741f56057c8a8741678",
  "chapterName": "Chapter 1",
  "concept": "Introduction to Node.js",
  "desc": "This chapter covers the basics of Node.js",
  "video": "https://example.com/intro-to-node",
  "uploadPdf": "https://example.com/chapter1.pdf"
} 
*/

  String? subjectId;
  String? chapterName;
  String? concept;
  String? desc;
  String? video;
  String? uploadPdf;

  ChapterModel({
    this.subjectId,
    this.chapterName,
    this.concept,
    this.desc,
    this.video,
    this.uploadPdf,
  });
  ChapterModel.fromJson(Map<String, dynamic> json) {
    subjectId = json['subjectId']?.toString();
    chapterName = json['chapterName']?.toString();
    concept = json['concept']?.toString();
    desc = json['desc']?.toString();
    video = json['video']?.toString();
    uploadPdf = json['uploadPdf']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subjectId'] = subjectId;
    data['chapterName'] = chapterName;
    data['concept'] = concept;
    data['desc'] = desc;
    data['video'] = video;
    data['uploadPdf'] = uploadPdf;
    return data;
  }
}
