import 'package:teaching_with_purpose/app/data/models/chapters_model_data.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ChaptersModel {
/*
{
  "status": true,
  "result": 7,
  "data": [
    {
      "_id": "658aa2a1bfee16190abc9b12",
      "subjectId": "6570261b8c2337e8d3e2e313",
      "chapterName": "Chapter three",
      "concept": "Story teller",
      "desc": "we discuss about story",
      "video": "https://angolazone.s3.ap-south-1.amazonaws.com/angolazone-SampleVideo_1280x720_1mb.mp4",
      "uploadPdf": "https://angolazone.s3.ap-south-1.amazonaws.com/angolazone-english.pdf",
      "isDeleted": false,
      "createdAt": "2023-12-26T09:53:37.539Z",
      "updatedAt": "2023-12-26T09:53:37.539Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ChaptersListModelData?>? data;

  ChaptersModel({
    this.status,
    this.result,
    this.data,
  });
  ChaptersModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ChaptersListModelData>[];
  v.forEach((v) {
  arr0.add(ChaptersListModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}

