import 'package:teaching_with_purpose/app/data/models/days_table_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ClassScheduleDataTimeTableSubjectTeacher {
/*
{
  "contactNumber": "9100000000",
  "_id": "657021118c2337e8d3e2e307",
  "joiningDate": "2023-12-06T07:20:35.124Z",
  "experience": "",
  "address": "",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "dob": "31",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Teachers",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2024-01-18T12:51:02.503Z",
  "__v": 0,
  "school": "65a52f67e6b1f330a3d7673d"
} 
*/

  String? contactNumber;
  String? Id;
  String? joiningDate;
  String? experience;
  String? address;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? school;

  ClassScheduleDataTimeTableSubjectTeacher({
    this.contactNumber,
    this.Id,
    this.joiningDate,
    this.experience,
    this.address,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.school,
  });
  ClassScheduleDataTimeTableSubjectTeacher.fromJson(Map<String, dynamic> json) {
    contactNumber = json['contactNumber']?.toString();
    Id = json['_id']?.toString();
    joiningDate = json['joiningDate']?.toString();
    experience = json['experience']?.toString();
    address = json['address']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    school = json['school']?.toString();
  }
}

class ClassScheduleDataTimeTableSubject {
/*
{
  "icon": "",
  "_id": "657025d48c2337e8d3e2e30d",
  "subject": "Mathmatics",
  "subjectCode": "123",
  "isDeleted": false,
  "createdAt": "2023-12-06T07:42:12.551Z",
  "updatedAt": "2023-12-06T07:42:12.551Z",
  "__v": 0
} 
*/

  String? icon;
  String? Id;
  String? subject;
  String? subjectCode;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleDataTimeTableSubject({
    this.icon,
    this.Id,
    this.subject,
    this.subjectCode,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleDataTimeTableSubject.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    subjectCode = json['subjectCode']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}


class ClassScheduleDataClassFaculitySubject {
/*
{
  "icon": "",
  "_id": "6570261b8c2337e8d3e2e313",
  "subject": "English",
  "subjectCode": "005",
  "isDeleted": false,
  "createdAt": "2023-12-06T07:43:23.213Z",
  "updatedAt": "2023-12-06T07:43:23.213Z",
  "__v": 0
} 
*/

  String? icon;
  String? Id;
  String? subject;
  String? subjectCode;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleDataClassFaculitySubject({
    this.icon,
    this.Id,
    this.subject,
    this.subjectCode,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleDataClassFaculitySubject.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    subjectCode = json['subjectCode']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }

}

class ClassScheduleDataClassFaculitySubjectTeacher {
/*
{
  "contactNumber": "9100000000",
  "_id": "657021118c2337e8d3e2e307",
  "joiningDate": "2023-12-06T07:20:35.124Z",
  "experience": "",
  "address": "",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "dob": "31",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Teachers",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2024-01-18T12:51:02.503Z",
  "__v": 0,
  "school": "65a52f67e6b1f330a3d7673d"
} 
*/

  String? contactNumber;
  String? Id;
  String? joiningDate;
  String? experience;
  String? address;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? school;

  ClassScheduleDataClassFaculitySubjectTeacher({
    this.contactNumber,
    this.Id,
    this.joiningDate,
    this.experience,
    this.address,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.school,
  });
  ClassScheduleDataClassFaculitySubjectTeacher.fromJson(Map<String, dynamic> json) {
    contactNumber = json['contactNumber']?.toString();
    Id = json['_id']?.toString();
    joiningDate = json['joiningDate']?.toString();
    experience = json['experience']?.toString();
    address = json['address']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    school = json['school']?.toString();
  }
}

class ClassScheduleDataClassFaculity {
/*
{
  "subjectTeacher": {
    "contactNumber": "9100000000",
    "_id": "657021118c2337e8d3e2e307",
    "joiningDate": "2023-12-06T07:20:35.124Z",
    "experience": "",
    "address": "",
    "name": "John Doe",
    "email": "teacher321@gmail.com",
    "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
    "gender": "Male",
    "dob": "31",
    "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
    "firebaseSignInProvider": "custom",
    "active": true,
    "isDeleted": false,
    "__t": "Teachers",
    "createdAt": "2023-12-06T07:21:53.404Z",
    "updatedAt": "2024-01-18T12:51:02.503Z",
    "__v": 0,
    "school": "65a52f67e6b1f330a3d7673d"
  },
  "subject": {
    "icon": "",
    "_id": "6570261b8c2337e8d3e2e313",
    "subject": "English",
    "subjectCode": "005",
    "isDeleted": false,
    "createdAt": "2023-12-06T07:43:23.213Z",
    "updatedAt": "2023-12-06T07:43:23.213Z",
    "__v": 0
  },
  "_id": "65d3019042db28a52371cb72"
} 
*/

  ClassScheduleDataClassFaculitySubjectTeacher? subjectTeacher;
  ClassScheduleDataClassFaculitySubject? subject;
  String? Id;

  ClassScheduleDataClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  ClassScheduleDataClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = (json['subjectTeacher'] != null) ? ClassScheduleDataClassFaculitySubjectTeacher.fromJson(json['subjectTeacher']) : null;
    subject = (json['subject'] != null) ? ClassScheduleDataClassFaculitySubject.fromJson(json['subject']) : null;
    Id = json['_id']?.toString();
  }
}

class ClassScheduleDataSubject {
/*
{
  "icon": "",
  "_id": "6570261b8c2337e8d3e2e313",
  "subject": "English",
  "subjectCode": "005",
  "isDeleted": false,
  "createdAt": "2023-12-06T07:43:23.213Z",
  "updatedAt": "2023-12-06T07:43:23.213Z",
  "__v": 0
} 
*/

  String? icon;
  String? Id;
  String? subject;
  String? subjectCode;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleDataSubject({
    this.icon,
    this.Id,
    this.subject,
    this.subjectCode,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleDataSubject.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    subjectCode = json['subjectCode']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }

}

class ClassScheduleDataClassTeacher {
/*
{
  "contactNumber": "9100000000",
  "_id": "657021118c2337e8d3e2e307",
  "joiningDate": "2023-12-06T07:20:35.124Z",
  "experience": "",
  "address": "",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "dob": "31",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Teachers",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2024-01-18T12:51:02.503Z",
  "__v": 0,
  "school": "65a52f67e6b1f330a3d7673d"
} 
*/

  String? contactNumber;
  String? Id;
  String? joiningDate;
  String? experience;
  String? address;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;
  String? school;

  ClassScheduleDataClassTeacher({
    this.contactNumber,
    this.Id,
    this.joiningDate,
    this.experience,
    this.address,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
    this.school,
  });
  ClassScheduleDataClassTeacher.fromJson(Map<String, dynamic> json) {
    contactNumber = json['contactNumber']?.toString();
    Id = json['_id']?.toString();
    joiningDate = json['joiningDate']?.toString();
    experience = json['experience']?.toString();
    address = json['address']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
    school = json['school']?.toString();
  }
}

class ClassScheduleDataSchool {
/*
{
  "icon": "",
  "_id": "65a52f67e6b1f330a3d7673d",
  "name": "new school data",
  "email": "newschoolData@yopmail.com",
  "address": "new address 56",
  "desc": "desc",
  "numberofStudents": 6,
  "numberofTeachers": 6,
  "active": true,
  "isDeleted": false,
  "createdAt": "2024-01-15T13:13:11.531Z",
  "updatedAt": "2024-01-15T13:13:11.531Z",
  "__v": 0
} 
*/

  String? icon;
  String? Id;
  String? name;
  String? email;
  String? address;
  String? desc;
  int? numberofStudents;
  int? numberofTeachers;
  bool? active;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleDataSchool({
    this.icon,
    this.Id,
    this.name,
    this.email,
    this.address,
    this.desc,
    this.numberofStudents,
    this.numberofTeachers,
    this.active,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleDataSchool.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    address = json['address']?.toString();
    desc = json['desc']?.toString();
    numberofStudents = json['numberofStudents']?.toInt();
    numberofTeachers = json['numberofTeachers']?.toInt();
    active = json['active'];
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ClassScheduleData {
/*
{
  "_id": "65d3019042db28a52371cb71",
  "school": {
    "icon": "",
    "_id": "65a52f67e6b1f330a3d7673d",
    "name": "new school data",
    "email": "newschoolData@yopmail.com",
    "address": "new address 56",
    "desc": "desc",
    "numberofStudents": 6,
    "numberofTeachers": 6,
    "active": true,
    "isDeleted": false,
    "createdAt": "2024-01-15T13:13:11.531Z",
    "updatedAt": "2024-01-15T13:13:11.531Z",
    "__v": 0
  },
  "classTeacher": {
    "contactNumber": "9100000000",
    "_id": "657021118c2337e8d3e2e307",
    "joiningDate": "2023-12-06T07:20:35.124Z",
    "experience": "",
    "address": "",
    "name": "John Doe",
    "email": "teacher321@gmail.com",
    "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
    "gender": "Male",
    "dob": "31",
    "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
    "firebaseSignInProvider": "custom",
    "active": true,
    "isDeleted": false,
    "__t": "Teachers",
    "createdAt": "2023-12-06T07:21:53.404Z",
    "updatedAt": "2024-01-18T12:51:02.503Z",
    "__v": 0,
    "school": "65a52f67e6b1f330a3d7673d"
  },
  "className": "8th",
  "section": "A",
  "subject": {
    "icon": "",
    "_id": "6570261b8c2337e8d3e2e313",
    "subject": "English",
    "subjectCode": "005",
    "isDeleted": false,
    "createdAt": "2023-12-06T07:43:23.213Z",
    "updatedAt": "2023-12-06T07:43:23.213Z",
    "__v": 0
  },
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": {
        "contactNumber": "9100000000",
        "_id": "657021118c2337e8d3e2e307",
        "joiningDate": "2023-12-06T07:20:35.124Z",
        "experience": "",
        "address": "",
        "name": "John Doe",
        "email": "teacher321@gmail.com",
        "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
        "gender": "Male",
        "dob": "31",
        "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
        "firebaseSignInProvider": "custom",
        "active": true,
        "isDeleted": false,
        "__t": "Teachers",
        "createdAt": "2023-12-06T07:21:53.404Z",
        "updatedAt": "2024-01-18T12:51:02.503Z",
        "__v": 0,
        "school": "65a52f67e6b1f330a3d7673d"
      },
      "subject": {
        "icon": "",
        "_id": "6570261b8c2337e8d3e2e313",
        "subject": "English",
        "subjectCode": "005",
        "isDeleted": false,
        "createdAt": "2023-12-06T07:43:23.213Z",
        "updatedAt": "2023-12-06T07:43:23.213Z",
        "__v": 0
      },
      "_id": "65d3019042db28a52371cb72"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subject": {
        "icon": "",
        "_id": "657025d48c2337e8d3e2e30d",
        "subject": "Mathmatics",
        "subjectCode": "123",
        "isDeleted": false,
        "createdAt": "2023-12-06T07:42:12.551Z",
        "updatedAt": "2023-12-06T07:42:12.551Z",
        "__v": 0
      },
      "subjectTeacher": {
        "contactNumber": "9100000000",
        "_id": "657021118c2337e8d3e2e307",
        "joiningDate": "2023-12-06T07:20:35.124Z",
        "experience": "",
        "address": "",
        "name": "John Doe",
        "email": "teacher321@gmail.com",
        "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
        "gender": "Male",
        "dob": "31",
        "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
        "firebaseSignInProvider": "custom",
        "active": true,
        "isDeleted": false,
        "__t": "Teachers",
        "createdAt": "2023-12-06T07:21:53.404Z",
        "updatedAt": "2024-01-18T12:51:02.503Z",
        "__v": 0,
        "school": "65a52f67e6b1f330a3d7673d"
      },
      "_id": "65d3019042db28a52371cb74"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-19T07:21:52.533Z",
  "updatedAt": "2024-02-19T07:21:52.533Z",
  "__v": 0
} 
*/

  String? Id;
  ClassScheduleDataSchool? school;
  ClassScheduleDataClassTeacher? classTeacher;
  String? className;
  String? section;
  ClassScheduleDataSubject? subject;
  int? classCapcity;
  List<ClassScheduleDataClassFaculity?>? classFaculity;
  List<DaysTableModel>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleData({
    this.Id,
    this.school,
    this.classTeacher,
    this.className,
    this.section,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    school = (json['school'] != null) ? ClassScheduleDataSchool.fromJson(json['school']) : null;
    classTeacher = (json['classTeacher'] != null) ? ClassScheduleDataClassTeacher.fromJson(json['classTeacher']) : null;
    className = json['className']?.toString();
    section = json['section']?.toString();
    subject = (json['subject'] != null) ? ClassScheduleDataSubject.fromJson(json['subject']) : null;
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <ClassScheduleDataClassFaculity>[];
  v.forEach((v) {
  arr0.add(ClassScheduleDataClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <DaysTableModel>[];
  v.forEach((v) {
  arr0.add(DaysTableModel.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ClassScheduleModel {
/*
{
  "status": true,
  "result": 2,
  "data": [
    {
      "_id": "65d3019042db28a52371cb71",
      "school": {
        "icon": "",
        "_id": "65a52f67e6b1f330a3d7673d",
        "name": "new school data",
        "email": "newschoolData@yopmail.com",
        "address": "new address 56",
        "desc": "desc",
        "numberofStudents": 6,
        "numberofTeachers": 6,
        "active": true,
        "isDeleted": false,
        "createdAt": "2024-01-15T13:13:11.531Z",
        "updatedAt": "2024-01-15T13:13:11.531Z",
        "__v": 0
      },
      "classTeacher": {
        "contactNumber": "9100000000",
        "_id": "657021118c2337e8d3e2e307",
        "joiningDate": "2023-12-06T07:20:35.124Z",
        "experience": "",
        "address": "",
        "name": "John Doe",
        "email": "teacher321@gmail.com",
        "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
        "gender": "Male",
        "dob": "31",
        "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
        "firebaseSignInProvider": "custom",
        "active": true,
        "isDeleted": false,
        "__t": "Teachers",
        "createdAt": "2023-12-06T07:21:53.404Z",
        "updatedAt": "2024-01-18T12:51:02.503Z",
        "__v": 0,
        "school": "65a52f67e6b1f330a3d7673d"
      },
      "className": "8th",
      "section": "A",
      "subject": {
        "icon": "",
        "_id": "6570261b8c2337e8d3e2e313",
        "subject": "English",
        "subjectCode": "005",
        "isDeleted": false,
        "createdAt": "2023-12-06T07:43:23.213Z",
        "updatedAt": "2023-12-06T07:43:23.213Z",
        "__v": 0
      },
      "classCapcity": 30,
      "classFaculity": [
        {
          "subjectTeacher": {
            "contactNumber": "9100000000",
            "_id": "657021118c2337e8d3e2e307",
            "joiningDate": "2023-12-06T07:20:35.124Z",
            "experience": "",
            "address": "",
            "name": "John Doe",
            "email": "teacher321@gmail.com",
            "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
            "gender": "Male",
            "dob": "31",
            "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
            "firebaseSignInProvider": "custom",
            "active": true,
            "isDeleted": false,
            "__t": "Teachers",
            "createdAt": "2023-12-06T07:21:53.404Z",
            "updatedAt": "2024-01-18T12:51:02.503Z",
            "__v": 0,
            "school": "65a52f67e6b1f330a3d7673d"
          },
          "subject": {
            "icon": "",
            "_id": "6570261b8c2337e8d3e2e313",
            "subject": "English",
            "subjectCode": "005",
            "isDeleted": false,
            "createdAt": "2023-12-06T07:43:23.213Z",
            "updatedAt": "2023-12-06T07:43:23.213Z",
            "__v": 0
          },
          "_id": "65d3019042db28a52371cb72"
        }
      ],
      "timeTable": [
        {
          "time": "10am-11am",
          "day": "monday",
          "subject": {
            "icon": "",
            "_id": "657025d48c2337e8d3e2e30d",
            "subject": "Mathmatics",
            "subjectCode": "123",
            "isDeleted": false,
            "createdAt": "2023-12-06T07:42:12.551Z",
            "updatedAt": "2023-12-06T07:42:12.551Z",
            "__v": 0
          },
          "subjectTeacher": {
            "contactNumber": "9100000000",
            "_id": "657021118c2337e8d3e2e307",
            "joiningDate": "2023-12-06T07:20:35.124Z",
            "experience": "",
            "address": "",
            "name": "John Doe",
            "email": "teacher321@gmail.com",
            "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
            "gender": "Male",
            "dob": "31",
            "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
            "firebaseSignInProvider": "custom",
            "active": true,
            "isDeleted": false,
            "__t": "Teachers",
            "createdAt": "2023-12-06T07:21:53.404Z",
            "updatedAt": "2024-01-18T12:51:02.503Z",
            "__v": 0,
            "school": "65a52f67e6b1f330a3d7673d"
          },
          "_id": "65d3019042db28a52371cb74"
        }
      ],
      "isDeleted": false,
      "createdAt": "2024-02-19T07:21:52.533Z",
      "updatedAt": "2024-02-19T07:21:52.533Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ClassScheduleData?>? data;

  ClassScheduleModel({
    this.status,
    this.result,
    this.data,
  });
  ClassScheduleModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ClassScheduleData>[];
  v.forEach((v) {
  arr0.add(ClassScheduleData.fromJson(v));
  });
    data = arr0;
    }
  }
}


