///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ClassModelDataTimeTable {
/*
{
  "time": "10am-11am",
  "day": "monday",
  "subject": "math",
  "subjectTeacher": "Noble",
  "_id": "6596536e2c5377156ebc3fc9"
} 
*/

  String? time;
  String? day;
  String? subject;
  String? subjectTeacher;
  String? Id;

  ClassModelDataTimeTable({
    this.time,
    this.day,
    this.subject,
    this.subjectTeacher,
    this.Id,
  });
  ClassModelDataTimeTable.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    day = json['day']?.toString();
    subject = json['subject']?.toString();
    subjectTeacher = json['subjectTeacher']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['day'] = day;
    data['subject'] = subject;
    data['subjectTeacher'] = subjectTeacher;
    data['_id'] = Id;
    return data;
  }
}

class ClassModelDataClassFaculity {
/*
{
  "subjectTeacher": "Suraj",
  "subject": "english",
  "_id": "6596536e2c5377156ebc3fc7"
} 
*/

  String? subjectTeacher;
  String? subject;
  String? Id;

  ClassModelDataClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  ClassModelDataClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = json['subjectTeacher']?.toString();
    subject = json['subject']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['subjectTeacher'] = subjectTeacher;
    data['subject'] = subject;
    data['_id'] = Id;
    return data;
  }
}

class ClassModelData {
/*
{
  "_id": "6596536e2c5377156ebc3fc6",
  "calssTeacher": "John",
  "className": "8-A",
  "subject": "english",
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": "Suraj",
      "subject": "english",
      "_id": "6596536e2c5377156ebc3fc7"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subject": "math",
      "subjectTeacher": "Noble",
      "_id": "6596536e2c5377156ebc3fc9"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-01-04T06:42:54.033Z",
  "updatedAt": "2024-01-04T06:42:54.033Z",
  "__v": 0
} 
*/

  String? Id;
  String? calssTeacher;
  String? className;
  String? subject;
  int? classCapcity;
  List<ClassModelDataClassFaculity?>? classFaculity;
  List<ClassModelDataTimeTable?>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassModelData({
    this.Id,
    this.calssTeacher,
    this.className,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    calssTeacher = json['calssTeacher']?.toString();
    className = json['className']?.toString();
    subject = json['subject']?.toString();
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <ClassModelDataClassFaculity>[];
  v.forEach((v) {
  arr0.add(ClassModelDataClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <ClassModelDataTimeTable>[];
  v.forEach((v) {
  arr0.add(ClassModelDataTimeTable.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['calssTeacher'] = calssTeacher;
    data['className'] = className;
    data['subject'] = subject;
    data['classCapcity'] = classCapcity;
    if (classFaculity != null) {
      final v = classFaculity;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['classFaculity'] = arr0;
    }
    if (timeTable != null) {
      final v = timeTable;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['timeTable'] = arr0;
    }
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class ClassModel {
/*
{
  "status": true,
  "result": 6,
  "data": [
    {
      "_id": "6596536e2c5377156ebc3fc6",
      "calssTeacher": "John",
      "className": "8-A",
      "subject": "english",
      "classCapcity": 30,
      "classFaculity": [
        {
          "subjectTeacher": "Suraj",
          "subject": "english",
          "_id": "6596536e2c5377156ebc3fc7"
        }
      ],
      "timeTable": [
        {
          "time": "10am-11am",
          "day": "monday",
          "subject": "math",
          "subjectTeacher": "Noble",
          "_id": "6596536e2c5377156ebc3fc9"
        }
      ],
      "isDeleted": false,
      "createdAt": "2024-01-04T06:42:54.033Z",
      "updatedAt": "2024-01-04T06:42:54.033Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ClassModelData?>? data;

  ClassModel({
    this.status,
    this.result,
    this.data,
  });
  ClassModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ClassModelData>[];
  v.forEach((v) {
  arr0.add(ClassModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
