import 'package:teaching_with_purpose/app/data/models/time_table_model.dart';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///

class ClassScheduleModelDataClassFaculity {
/*
{
  "subjectTeacher": "657021118c2337e8d3e2e307",
  "subject": "6570261b8c2337e8d3e2e313",
  "_id": "65d3019042db28a52371cb72"
} 
*/

  String? subjectTeacher;
  String? subject;
  String? Id;

  ClassScheduleModelDataClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  ClassScheduleModelDataClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = json['subjectTeacher']?.toString();
    subject = json['subject']?.toString();
    Id = json['_id']?.toString();
  }

}

class ClassScheduleModelData {
/*
{
  "_id": "65d3019042db28a52371cb71",
  "school": "65a52f67e6b1f330a3d7673d",
  "classTeacher": "657021118c2337e8d3e2e307",
  "className": "8th",
  "section": "A",
  "subject": "6570261b8c2337e8d3e2e313",
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "subject": "6570261b8c2337e8d3e2e313",
      "_id": "65d3019042db28a52371cb72"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subject": "657025d48c2337e8d3e2e30d",
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "_id": "65d3019042db28a52371cb74"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-19T07:21:52.533Z",
  "updatedAt": "2024-02-19T07:21:52.533Z",
  "__v": 0
} 
*/

  String? Id;
  String? school;
  String? classTeacher;
  String? className;
  String? section;
  String? subject;
  int? classCapcity;
  List<ClassScheduleModelDataClassFaculity?>? classFaculity;
  List<TimeTableModel?>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ClassScheduleModelData({
    this.Id,
    this.school,
    this.classTeacher,
    this.className,
    this.section,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ClassScheduleModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    school = json['school']?.toString();
    classTeacher = json['classTeacher']?.toString();
    className = json['className']?.toString();
    section = json['section']?.toString();
    subject = json['subject']?.toString();
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <ClassScheduleModelDataClassFaculity>[];
  v.forEach((v) {
  arr0.add(ClassScheduleModelDataClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <TimeTableModel>[];
  v.forEach((v) {
  arr0.add(TimeTableModel.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }

}

class ClassScheduleModel {
/*
{
  "status": true,
  "result": 2,
  "data": [
    {
      "_id": "65d3019042db28a52371cb71",
      "school": "65a52f67e6b1f330a3d7673d",
      "classTeacher": "657021118c2337e8d3e2e307",
      "className": "8th",
      "section": "A",
      "subject": "6570261b8c2337e8d3e2e313",
      "classCapcity": 30,
      "classFaculity": [
        {
          "subjectTeacher": "657021118c2337e8d3e2e307",
          "subject": "6570261b8c2337e8d3e2e313",
          "_id": "65d3019042db28a52371cb72"
        }
      ],
      "timeTable": [
        {
          "time": "10am-11am",
          "day": "monday",
          "subject": "657025d48c2337e8d3e2e30d",
          "subjectTeacher": "657021118c2337e8d3e2e307",
          "_id": "65d3019042db28a52371cb74"
        }
      ],
      "isDeleted": false,
      "createdAt": "2024-02-19T07:21:52.533Z",
      "updatedAt": "2024-02-19T07:21:52.533Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ClassScheduleModelData?>? data;

  ClassScheduleModel({
    this.status,
    this.result,
    this.data,
  });
  ClassScheduleModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ClassScheduleModelData>[];
  v.forEach((v) {
  arr0.add(ClassScheduleModelData.fromJson(v));
  });
    data = arr0;
    }
  }

}

