///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class EventsModelData {
/*
{
  "_id": "6578099f43e54ee273bb01ed",
  "name": "Sports Event",
  "date": "2023-12-31T12:00:00.000Z",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-jonathan-chng-751342-unsplash-e1554138342999.jpg",
  "desc": "Event description",
  "isDeleted": false,
  "createdAt": "2023-12-12T07:19:59.093Z",
  "updatedAt": "2023-12-12T07:37:49.298Z",
  "__v": 0
} 
*/

  String? Id;
  String? name;
  String? date;
  String? image;
  String? desc;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  EventsModelData({
    this.Id,
    this.name,
    this.date,
    this.image,
    this.desc,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  EventsModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    date = json['date']?.toString();
    image = json['image']?.toString();
    desc = json['desc']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['date'] = date;
    data['image'] = image;
    data['desc'] = desc;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class EventsModel {
/*
{
  "status": true,
  "result": 1,
  "data": [
    {
      "_id": "6578099f43e54ee273bb01ed",
      "name": "Sports Event",
      "date": "2023-12-31T12:00:00.000Z",
      "image": "https://angolazone.s3.amazonaws.com/angolazone-jonathan-chng-751342-unsplash-e1554138342999.jpg",
      "desc": "Event description",
      "isDeleted": false,
      "createdAt": "2023-12-12T07:19:59.093Z",
      "updatedAt": "2023-12-12T07:37:49.298Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<EventsModelData?>? data;

  EventsModel({
    this.status,
    this.result,
    this.data,
  });
  EventsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <EventsModelData>[];
  v.forEach((v) {
  arr0.add(EventsModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
