///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExamMarkModelDataMarkId {
/*
{
  "_id": "65a955b52ed04b0b03837d1d",
  "studentId": "65701e37b9cdbf994405ddae",
  "examType": "half-yearly",
  "marks": 75,
  "grade": "B",
  "passOrFail": "pass",
  "isDeleted": false,
  "createdAt": "2024-01-18T16:45:41.845Z",
  "updatedAt": "2024-01-18T16:45:41.845Z",
  "__v": 0
} 
*/

  String? Id;
  String? studentId;
  String? examType;
  int? marks;
  String? grade;
  String? passOrFail;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ExamMarkModelDataMarkId({
    this.Id,
    this.studentId,
    this.examType,
    this.marks,
    this.grade,
    this.passOrFail,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ExamMarkModelDataMarkId.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    studentId = json['studentId']?.toString();
    examType = json['examType']?.toString();
    marks = json['marks']?.toInt();
    grade = json['grade']?.toString();
    passOrFail = json['passOrFail']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ExamMarkModelDataClassTimeTable {
/*
{
  "time": "10am-11am",
  "day": "monday",
  "subject": "657025d48c2337e8d3e2e30d",
  "subjectTeacher": "657021118c2337e8d3e2e307",
  "_id": "65d3019042db28a52371cb74"
} 
*/

  String? time;
  String? day;
  String? subject;
  String? subjectTeacher;
  String? Id;

  ExamMarkModelDataClassTimeTable({
    this.time,
    this.day,
    this.subject,
    this.subjectTeacher,
    this.Id,
  });
  ExamMarkModelDataClassTimeTable.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    day = json['day']?.toString();
    subject = json['subject']?.toString();
    subjectTeacher = json['subjectTeacher']?.toString();
    Id = json['_id']?.toString();
  }
}

class ExamMarkModelDataClassClassFaculity {
/*
{
  "subjectTeacher": "657021118c2337e8d3e2e307",
  "subject": "6570261b8c2337e8d3e2e313",
  "_id": "65d3019042db28a52371cb72"
} 
*/

  String? subjectTeacher;
  String? subject;
  String? Id;

  ExamMarkModelDataClassClassFaculity({
    this.subjectTeacher,
    this.subject,
    this.Id,
  });
  ExamMarkModelDataClassClassFaculity.fromJson(Map<String, dynamic> json) {
    subjectTeacher = json['subjectTeacher']?.toString();
    subject = json['subject']?.toString();
    Id = json['_id']?.toString();
  }
}

class ExamMarkModelDataClass {
/*
{
  "_id": "65d3019042db28a52371cb71",
  "school": "65a52f67e6b1f330a3d7673d",
  "classTeacher": "657021118c2337e8d3e2e307",
  "className": "8th",
  "section": "A",
  "subject": "6570261b8c2337e8d3e2e313",
  "classCapcity": 30,
  "classFaculity": [
    {
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "subject": "6570261b8c2337e8d3e2e313",
      "_id": "65d3019042db28a52371cb72"
    }
  ],
  "timeTable": [
    {
      "time": "10am-11am",
      "day": "monday",
      "subject": "657025d48c2337e8d3e2e30d",
      "subjectTeacher": "657021118c2337e8d3e2e307",
      "_id": "65d3019042db28a52371cb74"
    }
  ],
  "isDeleted": false,
  "createdAt": "2024-02-19T07:21:52.533Z",
  "updatedAt": "2024-02-19T07:21:52.533Z",
  "__v": 0
} 
*/

  String? Id;
  String? school;
  String? classTeacher;
  String? className;
  String? section;
  String? subject;
  int? classCapcity;
  List<ExamMarkModelDataClassClassFaculity?>? classFaculity;
  List<ExamMarkModelDataClassTimeTable?>? timeTable;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ExamMarkModelDataClass({
    this.Id,
    this.school,
    this.classTeacher,
    this.className,
    this.section,
    this.subject,
    this.classCapcity,
    this.classFaculity,
    this.timeTable,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ExamMarkModelDataClass.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    school = json['school']?.toString();
    classTeacher = json['classTeacher']?.toString();
    className = json['className']?.toString();
    section = json['section']?.toString();
    subject = json['subject']?.toString();
    classCapcity = json['classCapcity']?.toInt();
  if (json['classFaculity'] != null) {
  final v = json['classFaculity'];
  final arr0 = <ExamMarkModelDataClassClassFaculity>[];
  v.forEach((v) {
  arr0.add(ExamMarkModelDataClassClassFaculity.fromJson(v));
  });
    classFaculity = arr0;
    }
  if (json['timeTable'] != null) {
  final v = json['timeTable'];
  final arr0 = <ExamMarkModelDataClassTimeTable>[];
  v.forEach((v) {
  arr0.add(ExamMarkModelDataClassTimeTable.fromJson(v));
  });
    timeTable = arr0;
    }
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ExamMarkModelDataSubject {
/*
{
  "icon": "",
  "_id": "6570261b8c2337e8d3e2e313",
  "subject": "English",
  "subjectCode": "005",
  "isDeleted": false,
  "createdAt": "2023-12-06T07:43:23.213Z",
  "updatedAt": "2023-12-06T07:43:23.213Z",
  "__v": 0
} 
*/

  String? icon;
  String? Id;
  String? subject;
  String? subjectCode;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ExamMarkModelDataSubject({
    this.icon,
    this.Id,
    this.subject,
    this.subjectCode,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ExamMarkModelDataSubject.fromJson(Map<String, dynamic> json) {
    icon = json['icon']?.toString();
    Id = json['_id']?.toString();
    subject = json['subject']?.toString();
    subjectCode = json['subjectCode']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ExamMarkModelData {
/*
{
  "_id": "65e1694df429291529827e9e",
  "subject": {
    "icon": "",
    "_id": "6570261b8c2337e8d3e2e313",
    "subject": "English",
    "subjectCode": "005",
    "isDeleted": false,
    "createdAt": "2023-12-06T07:43:23.213Z",
    "updatedAt": "2023-12-06T07:43:23.213Z",
    "__v": 0
  },
  "class": {
    "_id": "65d3019042db28a52371cb71",
    "school": "65a52f67e6b1f330a3d7673d",
    "classTeacher": "657021118c2337e8d3e2e307",
    "className": "8th",
    "section": "A",
    "subject": "6570261b8c2337e8d3e2e313",
    "classCapcity": 30,
    "classFaculity": [
      {
        "subjectTeacher": "657021118c2337e8d3e2e307",
        "subject": "6570261b8c2337e8d3e2e313",
        "_id": "65d3019042db28a52371cb72"
      }
    ],
    "timeTable": [
      {
        "time": "10am-11am",
        "day": "monday",
        "subject": "657025d48c2337e8d3e2e30d",
        "subjectTeacher": "657021118c2337e8d3e2e307",
        "_id": "65d3019042db28a52371cb74"
      }
    ],
    "isDeleted": false,
    "createdAt": "2024-02-19T07:21:52.533Z",
    "updatedAt": "2024-02-19T07:21:52.533Z",
    "__v": 0
  },
  "studentId": "65701e37b9cdbf994405ddae",
  "resultType": "live-quiz",
  "markId": {
    "_id": "65a955b52ed04b0b03837d1d",
    "studentId": "65701e37b9cdbf994405ddae",
    "examType": "half-yearly",
    "marks": 75,
    "grade": "B",
    "passOrFail": "pass",
    "isDeleted": false,
    "createdAt": "2024-01-18T16:45:41.845Z",
    "updatedAt": "2024-01-18T16:45:41.845Z",
    "__v": 0
  },
  "topic": "Grammar",
  "remarks": "Excellent performance!",
  "performance": "excellent",
  "isDeleted": false,
  "createdAt": "2024-03-01T05:36:13.707Z",
  "updatedAt": "2024-03-01T05:36:13.707Z",
  "__v": 0
} 
*/

  String? Id;
  ExamMarkModelDataSubject? subject;
  ExamMarkModelDataClass? theClass;
  String? studentId;
  String? resultType;
  ExamMarkModelDataMarkId? markId;
  String? topic;
  String? remarks;
  String? performance;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ExamMarkModelData({
    this.Id,
    this.subject,
    this.theClass,
    this.studentId,
    this.resultType,
    this.markId,
    this.topic,
    this.remarks,
    this.performance,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ExamMarkModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    subject = (json['subject'] != null) ? ExamMarkModelDataSubject.fromJson(json['subject']) : null;
    theClass = (json['class'] != null) ? ExamMarkModelDataClass.fromJson(json['class']) : null;
    studentId = json['studentId']?.toString();
    resultType = json['resultType']?.toString();
    markId = (json['markId'] != null) ? ExamMarkModelDataMarkId.fromJson(json['markId']) : null;
    topic = json['topic']?.toString();
    remarks = json['remarks']?.toString();
    performance = json['performance']?.toString();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
}

class ExamMarkModel {
/*
{
  "status": true,
  "result": 1,
  "data": [
    {
      "_id": "65e1694df429291529827e9e",
      "subject": {
        "icon": "",
        "_id": "6570261b8c2337e8d3e2e313",
        "subject": "English",
        "subjectCode": "005",
        "isDeleted": false,
        "createdAt": "2023-12-06T07:43:23.213Z",
        "updatedAt": "2023-12-06T07:43:23.213Z",
        "__v": 0
      },
      "class": {
        "_id": "65d3019042db28a52371cb71",
        "school": "65a52f67e6b1f330a3d7673d",
        "classTeacher": "657021118c2337e8d3e2e307",
        "className": "8th",
        "section": "A",
        "subject": "6570261b8c2337e8d3e2e313",
        "classCapcity": 30,
        "classFaculity": [
          {
            "subjectTeacher": "657021118c2337e8d3e2e307",
            "subject": "6570261b8c2337e8d3e2e313",
            "_id": "65d3019042db28a52371cb72"
          }
        ],
        "timeTable": [
          {
            "time": "10am-11am",
            "day": "monday",
            "subject": "657025d48c2337e8d3e2e30d",
            "subjectTeacher": "657021118c2337e8d3e2e307",
            "_id": "65d3019042db28a52371cb74"
          }
        ],
        "isDeleted": false,
        "createdAt": "2024-02-19T07:21:52.533Z",
        "updatedAt": "2024-02-19T07:21:52.533Z",
        "__v": 0
      },
      "studentId": "65701e37b9cdbf994405ddae",
      "resultType": "live-quiz",
      "markId": {
        "_id": "65a955b52ed04b0b03837d1d",
        "studentId": "65701e37b9cdbf994405ddae",
        "examType": "half-yearly",
        "marks": 75,
        "grade": "B",
        "passOrFail": "pass",
        "isDeleted": false,
        "createdAt": "2024-01-18T16:45:41.845Z",
        "updatedAt": "2024-01-18T16:45:41.845Z",
        "__v": 0
      },
      "topic": "Grammar",
      "remarks": "Excellent performance!",
      "performance": "excellent",
      "isDeleted": false,
      "createdAt": "2024-03-01T05:36:13.707Z",
      "updatedAt": "2024-03-01T05:36:13.707Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ExamMarkModelData?>? data;

  ExamMarkModel({
    this.status,
    this.result,
    this.data,
  });
  ExamMarkModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ExamMarkModelData>[];
  v.forEach((v) {
  arr0.add(ExamMarkModelData.fromJson(v));
  });
    data = arr0;
    }
  }
}
