///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ExamSheetModelData {
/*
{
  "_id": "659535a0a4aa3b48a6527fa3",
  "className": "8-A",
  "examTitle": "Midterm Exam",
  "examTime": "09:00 AM to 12:00 PM",
  "examDate": "2024-01-03T10:21:47.047Z",
  "examDuration": "2 hours",
  "passingMarks": 20,
  "fullMarks": 50,
  "isDeleted": false,
  "createdAt": "2024-01-03T10:23:28.499Z",
  "updatedAt": "2024-01-03T10:23:28.499Z",
  "__v": 0
} 
*/

  String? Id;
  String? className;
  String? examTitle;
  String? examTime;
  String? examDate;
  String? examDuration;
  int? passingMarks;
  int? fullMarks;
  bool? isDeleted;
  String? createdAt;
  String? updatedAt;
  int? V;

  ExamSheetModelData({
    this.Id,
    this.className,
    this.examTitle,
    this.examTime,
    this.examDate,
    this.examDuration,
    this.passingMarks,
    this.fullMarks,
    this.isDeleted,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  ExamSheetModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    className = json['className']?.toString();
    examTitle = json['examTitle']?.toString();
    examTime = json['examTime']?.toString();
    examDate = json['examDate']?.toString();
    examDuration = json['examDuration']?.toString();
    passingMarks = json['passingMarks']?.toInt();
    fullMarks = json['fullMarks']?.toInt();
    isDeleted = json['isDeleted'];
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['className'] = className;
    data['examTitle'] = examTitle;
    data['examTime'] = examTime;
    data['examDate'] = examDate;
    data['examDuration'] = examDuration;
    data['passingMarks'] = passingMarks;
    data['fullMarks'] = fullMarks;
    data['isDeleted'] = isDeleted;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class ExamSheetModel {
/*
{
  "status": true,
  "result": 3,
  "data": [
    {
      "_id": "659535a0a4aa3b48a6527fa3",
      "className": "8-A",
      "examTitle": "Midterm Exam",
      "examTime": "09:00 AM to 12:00 PM",
      "examDate": "2024-01-03T10:21:47.047Z",
      "examDuration": "2 hours",
      "passingMarks": 20,
      "fullMarks": 50,
      "isDeleted": false,
      "createdAt": "2024-01-03T10:23:28.499Z",
      "updatedAt": "2024-01-03T10:23:28.499Z",
      "__v": 0
    }
  ]
} 
*/

  bool? status;
  int? result;
  List<ExamSheetModelData?>? data;

  ExamSheetModel({
    this.status,
    this.result,
    this.data,
  });
  ExamSheetModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    result = json['result']?.toInt();
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <ExamSheetModelData>[];
  v.forEach((v) {
  arr0.add(ExamSheetModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['result'] = result;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}