///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class QuizQuestion {
/*
{
  "questionText": "Who wrote Hamlet?",
  "answer": 1,
  "points": 10,
  "options": [
    "Shakespeare"
  ]
} 
*/

  String? questionText;
  int? answer;
  int? points;
  List<String?>? options;

  QuizQuestion({
    this.questionText,
    this.answer,
    this.points,
    this.options,
  });
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['questionText'] = questionText;
    data['answer'] = answer;
    data['points'] = points;
    if (options != null) {
      final v = options;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v);
  }
      data['options'] = arr0;
    }
    return data;
  }
}
