///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class StudentsModelData {
/*
{
  "_id": "65701e37b9cdbf994405ddae",
  "school": "Sample School",
  "district": "Sample District",
  "districtStudentID": "123456",
  "stateStudentID": "7890",
  "name": "suraj singh",
  "className": "8-A",
  "rollNumber": 15,
  "email": "student321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-teacherimg.png",
  "gender": "Male",
  "firebaseUid": "tRs34G9tTTbDXnm34i2oCdSNgj03",
  "firebaseSignInProvider": "custom",
  "createdAt": "2023-12-06T07:09:43.682Z",
  "updatedAt": "2023-12-08T13:43:32.784Z"
} 
*/

  String? Id;
  String? school;
  String? district;
  String? districtStudentID;
  String? stateStudentID;
  String? name;
  String? className;
  int? rollNumber;
  String? email;
  String? image;
  String? gender;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? createdAt;
  String? updatedAt;

  StudentsModelData({
    this.Id,
    this.school,
    this.district,
    this.districtStudentID,
    this.stateStudentID,
    this.name,
    this.className,
    this.rollNumber,
    this.email,
    this.image,
    this.gender,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.createdAt,
    this.updatedAt,
  });
  StudentsModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    school = json['school']?.toString();
    district = json['district']?.toString();
    districtStudentID = json['districtStudentID']?.toString();
    stateStudentID = json['stateStudentID']?.toString();
    name = json['name']?.toString();
    className = json['className']?.toString();
    rollNumber = json['rollNumber']?.toInt();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['school'] = school;
    data['district'] = district;
    data['districtStudentID'] = districtStudentID;
    data['stateStudentID'] = stateStudentID;
    data['name'] = name;
    data['className'] = className;
    data['rollNumber'] = rollNumber;
    data['email'] = email;
    data['image'] = image;
    data['gender'] = gender;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class StudentsModel {
/*
{
  "status": true,
  "data": [
    {
      "_id": "65701e37b9cdbf994405ddae",
      "school": "Sample School",
      "district": "Sample District",
      "districtStudentID": "123456",
      "stateStudentID": "7890",
      "name": "suraj singh",
      "className": "8-A",
      "rollNumber": 15,
      "email": "student321@gmail.com",
      "image": "https://angolazone.s3.amazonaws.com/angolazone-teacherimg.png",
      "gender": "Male",
      "firebaseUid": "tRs34G9tTTbDXnm34i2oCdSNgj03",
      "firebaseSignInProvider": "custom",
      "createdAt": "2023-12-06T07:09:43.682Z",
      "updatedAt": "2023-12-08T13:43:32.784Z"
    }
  ]
} 
*/

  bool? status;
  List<StudentsModelData?>? data;

  StudentsModel({
    this.status,
    this.data,
  });
  StudentsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <StudentsModelData>[];
  v.forEach((v) {
  arr0.add(StudentsModelData.fromJson(v));
  });
    data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['data'] = arr0;
    }
    return data;
  }
}
