///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TeacherDetailsModelData {
/*
{
  "_id": "657021118c2337e8d3e2e307",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2023-12-06T07:21:53.404Z"
} 
*/

  String? Id;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? firebaseUid;
  String? firebaseSignInProvider;
  String? createdAt;
  String? updatedAt;

  TeacherDetailsModelData({
    this.Id,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.createdAt,
    this.updatedAt,
  });
  TeacherDetailsModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['email'] = email;
    data['image'] = image;
    data['gender'] = gender;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    return data;
  }
}

class TeacherDetailsModel {
/*
{
  "status": true,
  "data": [
    {
      "_id": "657021118c2337e8d3e2e307",
      "name": "John Doe",
      "email": "teacher321@gmail.com",
      "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
      "gender": "Male",
      "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
      "firebaseSignInProvider": "custom",
      "createdAt": "2023-12-06T07:21:53.404Z",
      "updatedAt": "2023-12-06T07:21:53.404Z"
    }
  ]
} 
*/

  bool? status;
  List<TeacherDetailsModelData?>? data;

  TeacherDetailsModel({
    this.status,
    this.data,
  });
  TeacherDetailsModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
  if (json['data'] != null) {
  final v = json['data'];
  final arr0 = <TeacherDetailsModelData>[];
  v.forEach((v) {
  arr0.add(TeacherDetailsModelData.fromJson(v));
  });
    this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['data'] = arr0;
    }
    return data;
  }
}
