///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TeacherDetailsUploadModelData {
/*
{
  "_id": "657021118c2337e8d3e2e307",
  "joiningDate": "2023-12-06T07:20:35.124Z",
  "experience": "",
  "subject": "",
  "address": "",
  "name": "John Doe",
  "email": "teacher321@gmail.com",
  "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
  "gender": "Male",
  "dob": "",
  "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
  "firebaseSignInProvider": "custom",
  "active": true,
  "isDeleted": false,
  "__t": "Teachers",
  "createdAt": "2023-12-06T07:21:53.404Z",
  "updatedAt": "2024-01-04T13:51:00.845Z",
  "__v": 0
} 
*/

  String? Id;
  String? joiningDate;
  String? experience;
  String? subject;
  String? address;
  String? name;
  String? email;
  String? image;
  String? gender;
  String? dob;
  String? firebaseUid;
  String? firebaseSignInProvider;
  bool? active;
  bool? isDeleted;
  String? T;
  String? createdAt;
  String? updatedAt;
  int? V;

  TeacherDetailsUploadModelData({
    this.Id,
    this.joiningDate,
    this.experience,
    this.subject,
    this.address,
    this.name,
    this.email,
    this.image,
    this.gender,
    this.dob,
    this.firebaseUid,
    this.firebaseSignInProvider,
    this.active,
    this.isDeleted,
    this.T,
    this.createdAt,
    this.updatedAt,
    this.V,
  });
  TeacherDetailsUploadModelData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    joiningDate = json['joiningDate']?.toString();
    experience = json['experience']?.toString();
    subject = json['subject']?.toString();
    address = json['address']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    image = json['image']?.toString();
    gender = json['gender']?.toString();
    dob = json['dob']?.toString();
    firebaseUid = json['firebaseUid']?.toString();
    firebaseSignInProvider = json['firebaseSignInProvider']?.toString();
    active = json['active'];
    isDeleted = json['isDeleted'];
    T = json['__t']?.toString();
    createdAt = json['createdAt']?.toString();
    updatedAt = json['updatedAt']?.toString();
    V = json['__v']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['joiningDate'] = joiningDate;
    data['experience'] = experience;
    data['subject'] = subject;
    data['address'] = address;
    data['name'] = name;
    data['email'] = email;
    data['image'] = image;
    data['gender'] = gender;
    data['dob'] = dob;
    data['firebaseUid'] = firebaseUid;
    data['firebaseSignInProvider'] = firebaseSignInProvider;
    data['active'] = active;
    data['isDeleted'] = isDeleted;
    data['__t'] = T;
    data['createdAt'] = createdAt;
    data['updatedAt'] = updatedAt;
    data['__v'] = V;
    return data;
  }
}

class TeacherDetailsUploadModel {
/*
{
  "status": true,
  "data": {
    "_id": "657021118c2337e8d3e2e307",
    "joiningDate": "2023-12-06T07:20:35.124Z",
    "experience": "",
    "subject": "",
    "address": "",
    "name": "John Doe",
    "email": "teacher321@gmail.com",
    "image": "https://angolazone.s3.amazonaws.com/angolazone-User-Profile-PNG-High-Quality-Image.png.crdownload",
    "gender": "Male",
    "dob": "",
    "firebaseUid": "wpnCVSW0MwQjAtkArhznsLWSNnq1",
    "firebaseSignInProvider": "custom",
    "active": true,
    "isDeleted": false,
    "__t": "Teachers",
    "createdAt": "2023-12-06T07:21:53.404Z",
    "updatedAt": "2024-01-04T13:51:00.845Z",
    "__v": 0
  }
} 
*/

  bool? status;
  TeacherDetailsUploadModelData? data;

  TeacherDetailsUploadModel({
    this.status,
    this.data,
  });
  TeacherDetailsUploadModel.fromJson(Map<String, dynamic> json) {
    status = json['status'];
    data = (json['data'] != null) ? TeacherDetailsUploadModelData.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
