///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class TimeTableModel {
/*
{
  "time": "10am-11am",
  "day": "monday",
  "subject": "math",
  "subjectTeacher": "Noble",
  "_id": "6596536e2c5377156ebc3fc9"
} 
*/

  String? time;
  String? day;
  String? subject;
  String? subjectTeacher;
  String? Id;

  TimeTableModel({
    this.time,
    this.day,
    this.subject,
    this.subjectTeacher,
    this.Id,
  });
  TimeTableModel.fromJson(Map<String, dynamic> json) {
    time = json['time']?.toString();
    day = json['day']?.toString();
    subject = json['subject']?.toString();
    subjectTeacher = json['subjectTeacher']?.toString();
    Id = json['_id']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['day'] = day;
    data['subject'] = subject;
    data['subjectTeacher'] = subjectTeacher;
    data['_id'] = Id;
    return data;
  }
}
