// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-GSvfVE7ndVIuGHSkczpgxuIxRY8ukgg',
    appId: '1:807755555915:android:4e9a74494054a771ce99ce',
    messagingSenderId: '807755555915',
    projectId: 'learning-with-purpose-adc7e',
    storageBucket: 'learning-with-purpose-adc7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6h_X2MGVe0TZAjBzudG-Cbim4OV1Pefw',
    appId: '1:807755555915:ios:57405fb5b7abf2b5ce99ce',
    messagingSenderId: '807755555915',
    projectId: 'learning-with-purpose-adc7e',
    storageBucket: 'learning-with-purpose-adc7e.appspot.com',
    androidClientId: '807755555915-q3oiencj36er4g6s366b6hjcmo2pk5hc.apps.googleusercontent.com',
    iosClientId: '807755555915-otlvefv1451rm64qaf2fiv7m20be1td6.apps.googleusercontent.com',
    iosBundleId: 'com.example.teachingWithPurpose',
  );
}
