part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const ON_BOARD = _Paths.ON_BOARD;
  static const GET_STARTED = _Paths.GET_STARTED;
  static const LOGIN = _Paths.LOGIN;
  static const BOTTOM_NAV = _Paths.BOTTOM_NAV;
  static const FORGOT_PASSWORD = _Paths.FORGOT_PASSWORD;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const CHANGE_PASS_SUCESS = _Paths.CHANGE_PASS_SUCESS;
  static const SCHEDULE = _Paths.SCHEDULE;
  static const EXAM_DATE_SHEET = _Paths.EXAM_DATE_SHEET;
  static const PROFILE = _Paths.PROFILE;
  static const VERIFY = _Paths.VERIFY;
  static const HELP_CENTER = _Paths.HELP_CENTER;
  static const ATTENDANCE = _Paths.ATTENDANCE;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const MY_CLASSES = _Paths.MY_CLASSES;
  static const STUDENT_DETAILS = _Paths.STUDENT_DETAILS;
  static const COURCE_COMPLETION = _Paths.COURCE_COMPLETION;
  static const ASSIGNMENT_COMPLETION = _Paths.ASSIGNMENT_COMPLETION;
  static const EXAM_TRACKING = _Paths.EXAM_TRACKING;
  static const STUDENT_BECHAVIOUR = _Paths.STUDENT_BECHAVIOUR;
  static const ASSIGNMENTS = _Paths.ASSIGNMENTS;
  static const ASSIGNMENT_UPLODED = _Paths.ASSIGNMENT_UPLODED;
  static const SUBJECTS = _Paths.SUBJECTS;
  static const CHAPTER = _Paths.CHAPTER;
  static const ADD_CHAPTERS = _Paths.ADD_CHAPTERS;
  static const ADD_QUESTIONS = _Paths.ADD_QUESTIONS;
  static const RESULTS = _Paths.RESULTS;
  static const LIVE_QUIZZ = _Paths.LIVE_QUIZZ;
  static const LIVE_QUIZZ_SUCESS = _Paths.LIVE_QUIZZ_SUCESS;
  static const MARKS = _Paths.MARKS;
  static const EVENTS = _Paths.EVENTS;
  static const ANNOUNCEMENTS = _Paths.ANNOUNCEMENTS;
  static const ADD_ASSIGNMENT = _Paths.ADD_ASSIGNMENT;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const ON_BOARD = '/on-board';
  static const GET_STARTED = '/get-started';
  static const LOGIN = '/login';
  static const BOTTOM_NAV = '/bottom-nav';
  static const FORGOT_PASSWORD = '/forgot-password';
  static const CHANGE_PASSWORD = '/change-password';
  static const CHANGE_PASS_SUCESS = '/change-pass-sucess';
  static const SCHEDULE = '/schedule';
  static const EXAM_DATE_SHEET = '/exam-date-sheet';
  static const PROFILE = '/profile';
  static const VERIFY = '/verify';
  static const HELP_CENTER = '/help-center';
  static const ATTENDANCE = '/attendance';
  static const EDIT_PROFILE = '/edit-profile';
  static const MY_CLASSES = '/my-classes';
  static const STUDENT_DETAILS = '/student-details';
  static const COURCE_COMPLETION = '/cource-complection';
  static const ASSIGNMENT_COMPLETION = '/assignment-completion';
  static const EXAM_TRACKING = '/exam-tracking';
  static const STUDENT_BECHAVIOUR = '/student-behaviour';
  static const ASSIGNMENTS = '/assignments';
  static const ASSIGNMENT_UPLODED = '/assignment-uploded';
  static const SUBJECTS = '/subjects';
  static const CHAPTER = '/chapter';
  static const ADD_CHAPTERS = '/add-chapters';
  static const ADD_QUESTIONS = '/add-questions';
  static const RESULTS = '/results';
  static const LIVE_QUIZZ = '/live-quizz';
  static const LIVE_QUIZZ_SUCESS = '/live-quiz-sucess';
  static const MARKS = '/marks';
  static const EVENTS = '/events';
  static const ANNOUNCEMENTS = '/announcements';
  static const ADD_ASSIGNMENT = '/add-assignment';
}
